name: Scrape futbolred website

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "0 */4 * * *"
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with: 
          version: 7.18.2
          run_install: true
      - run: |
          node scraping/index.js
          git config user.name futbol-red-bot
          git add -A
          git commit -m "[bot] Update Futbolred Database"
          git push -u origin main